version: '2'
services:
    angularsupremev3-app:
        image: angularsupremev3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://angularsupremev3-mysql:3306/angularsupremev3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angularsupremev3-mysql:
        extends:
            file: mysql.yml
            service: angularsupremev3-mysql
